# Generated by Django 2.2 on 2020-06-30 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='static/videos')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
