# Generated by Django 2.2 on 2020-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20200701_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_millisecond',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_source_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'Image'), ('V', 'Video')], max_length=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='static/video'),
        ),
    ]
